services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - app1
      - app2
  app1:
    build:
      context: ./apps/app1
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    volumes:
      - ./apps/app1:/app
  app2:
    build:
      context: ./apps/app2
      dockerfile: Dockerfile
    environment:
      PORT: 8081
    volumes:
      - ./apps/app2:/app
