services:
  app1:
    build:
      context: ./apps/app1
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./apps/app1:/app
  app2:
    build:
      context: ./apps/app2
      dockerfile: Dockerfile
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - ./apps/app2:/app
